{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dws.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}