{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "dws.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "dws.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dws.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
spec:
  podSelector:
    matchLabels:
      {{- include "dws.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.app.port }}
      {{- with .Values.networkPolicy.ingress.from }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- with .Values.networkPolicy.egress.to }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}