apiVersion: apps/v1
kind: Deployment
metadata:
  name: dws-deployment
  namespace: dws
spec:
  template:
    spec:
      containers:
      - name: dws
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: dws-environment-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: dws-environment-config
              key: LOG_LEVEL