name: "US Government Classification Detection"
description: "Rules for detecting classified national security information markings"
version: "1.0"

rules:
  # Classification Level Detection
  - name: "TOP_SECRET_DETECTION"
    description: "Detects TOP SECRET classification markings"
    type: "regex"
    pattern: "(?i)\\b(TOP\\s*SECRET|TS)\\b"
    severity: "CRITICAL"
    category: "CLASSIFICATION"
    tags: ["classification", "top-secret", "national-security"]
    
  - name: "SECRET_DETECTION"
    description: "Detects SECRET classification markings"
    type: "regex"
    pattern: "(?i)\\b(SECRET|S)(?!\\s*(SERVICE|SOCIETY|SYSTEM))\\b"
    severity: "HIGH"
    category: "CLASSIFICATION"
    tags: ["classification", "secret", "national-security"]
    
  - name: "CONFIDENTIAL_DETECTION"
    description: "Detects CONFIDENTIAL classification markings"
    type: "regex"
    pattern: "(?i)\\b(CONFIDENTIAL|C)(?!\\s*(COMPANY|CORPORATION|COPYRIGHT))\\b"
    severity: "MEDIUM"
    category: "CLASSIFICATION"
    tags: ["classification", "confidential", "national-security"]

  # Banner Markings
  - name: "CLASSIFICATION_BANNER"
    description: "Detects classification banners at document headers"
    type: "regex"
    pattern: "^\\s*(TOP\\s*SECRET|SECRET|CONFIDENTIAL)(?:\\s*//\\s*[A-Z\\s,/-]+)?\\s*$"
    severity: "HIGH"
    category: "BANNER_MARKING"
    tags: ["banner", "classification", "header"]
    
  - name: "CLASSIFICATION_FOOTER"
    description: "Detects classification markings in document footers"
    type: "regex"
    pattern: "\\b(TOP\\s*SECRET|SECRET|CONFIDENTIAL)\\s*$"
    severity: "HIGH"
    category: "BANNER_MARKING"
    tags: ["banner", "classification", "footer"]

  # Portion Markings
  - name: "PORTION_MARKING_TS"
    description: "Detects TOP SECRET portion markings"
    type: "regex"
    pattern: "\\(TS\\)"
    severity: "CRITICAL"
    category: "PORTION_MARKING"
    tags: ["portion-marking", "top-secret"]
    
  - name: "PORTION_MARKING_S"
    description: "Detects SECRET portion markings"
    type: "regex"
    pattern: "\\(S\\)"
    severity: "HIGH"
    category: "PORTION_MARKING"
    tags: ["portion-marking", "secret"]
    
  - name: "PORTION_MARKING_C"
    description: "Detects CONFIDENTIAL portion markings"
    type: "regex"
    pattern: "\\(C\\)"
    severity: "MEDIUM"
    category: "PORTION_MARKING"
    tags: ["portion-marking", "confidential"]
    
  - name: "PORTION_MARKING_U"
    description: "Detects UNCLASSIFIED portion markings"
    type: "regex"
    pattern: "\\(U\\)"
    severity: "LOW"
    category: "PORTION_MARKING"
    tags: ["portion-marking", "unclassified"]
    
  # Complex Portion Markings with Dissemination Controls
  - name: "PORTION_MARKING_TS_SCI"
    description: "Detects TOP SECRET//SCI portion markings"
    type: "regex"
    pattern: "\\(TS//SI[A-Z-]*\\)"
    severity: "CRITICAL"
    category: "PORTION_MARKING"
    tags: ["portion-marking", "top-secret", "sci"]
    
  - name: "PORTION_MARKING_WITH_CONTROLS"
    description: "Detects portion markings with dissemination controls"
    type: "regex"
    pattern: "\\((TS|S|C)//[A-Z\\s,/-]+\\)"
    severity: "HIGH"
    category: "PORTION_MARKING"
    tags: ["portion-marking", "dissemination-control"]

  # Dissemination Control Markings
  - name: "NOFORN_MARKING"
    description: "Detects NOFORN (Not Releasable to Foreign Nationals) markings"
    type: "regex"
    pattern: "\\b(NOFORN|NOT\\s*RELEASABLE\\s*TO\\s*FOREIGN\\s*NATIONALS)\\b"
    severity: "HIGH"
    category: "DISSEMINATION_CONTROL"
    tags: ["noforn", "dissemination-control"]
    
  - name: "NOCONTRACT_MARKING"
    description: "Detects NOCONTRACT (Not Releasable to Contractors) markings"
    type: "regex"
    pattern: "\\b(NOCONTRACT|NOT\\s*RELEASABLE\\s*TO\\s*CONTRACTORS)\\b"
    severity: "HIGH"
    category: "DISSEMINATION_CONTROL"
    tags: ["nocontract", "dissemination-control"]
    
  - name: "DISPLAYONLY_MARKING"
    description: "Detects DISPLAY ONLY markings"
    type: "regex"
    pattern: "\\b(DISPLAY\\s*ONLY)\\b"
    severity: "MEDIUM"
    category: "DISSEMINATION_CONTROL"
    tags: ["display-only", "dissemination-control"]
    
  - name: "ORCON_MARKING"
    description: "Detects ORCON (Originator Controlled) markings"
    type: "regex"
    pattern: "\\b(ORCON|ORIGINATOR\\s*CONTROLLED)\\b"
    severity: "HIGH"
    category: "DISSEMINATION_CONTROL"
    tags: ["orcon", "dissemination-control"]
    
  - name: "PROPIN_MARKING"
    description: "Detects PROPIN (Proprietary Information Involved) markings"
    type: "regex"
    pattern: "\\b(PROPIN|PROPRIETARY\\s*INFORMATION\\s*INVOLVED)\\b"
    severity: "MEDIUM"
    category: "DISSEMINATION_CONTROL"
    tags: ["propin", "dissemination-control"]
    
  - name: "REL_TO_MARKING"
    description: "Detects REL TO (Releasable To) markings"
    type: "regex"
    pattern: "\\b(REL\\s*TO\\s*[A-Z,\\s]+|RELEASABLE\\s*TO\\s*[A-Z,\\s]+)\\b"
    severity: "MEDIUM"
    category: "DISSEMINATION_CONTROL"
    tags: ["rel-to", "dissemination-control"]
    
  - name: "EYES_ONLY_MARKING"
    description: "Detects EYES ONLY markings"
    type: "regex"
    pattern: "\\b(EYES\\s*ONLY)\\b"
    severity: "HIGH"
    category: "DISSEMINATION_CONTROL"
    tags: ["eyes-only", "dissemination-control"]

  # SCI (Sensitive Compartmented Information) Markings
  - name: "SCI_MARKING"
    description: "Detects SCI compartment markings"
    type: "regex"
    pattern: "\\b(SCI|SENSITIVE\\s*COMPARTMENTED\\s*INFORMATION)\\b"
    severity: "CRITICAL"
    category: "SCI"
    tags: ["sci", "compartmented"]
    
  - name: "SI_COMPARTMENTS"
    description: "Detects specific SI compartment markings"
    type: "regex"
    pattern: "\\b(SI-[A-Z]+|TALENT\\s*KEYHOLE|TK|GAMMA|ORION)\\b"
    severity: "CRITICAL"
    category: "SCI"
    tags: ["si-compartments", "sci"]
    
  - name: "SAR_MARKING"
    description: "Detects SAR (Special Access Required) markings"
    type: "regex"
    pattern: "\\b(SAR|SPECIAL\\s*ACCESS\\s*REQUIRED)\\b"
    severity: "CRITICAL"
    category: "SAR"
    tags: ["sar", "special-access"]
    
  - name: "SAP_MARKING"
    description: "Detects Special Access Program markings"
    type: "regex"
    pattern: "\\b(SAP|SPECIAL\\s*ACCESS\\s*PROGRAM)\\b"
    severity: "CRITICAL"
    category: "SAP"
    tags: ["sap", "special-access"]

  # Classification Authority
  - name: "CLASSIFICATION_AUTHORITY"
    description: "Detects classification authority references"
    type: "regex"
    pattern: "(?i)(Classified\\s*By:|Derived\\s*From:|Declassify\\s*On:)"
    severity: "MEDIUM"
    category: "CLASSIFICATION_AUTHORITY"
    tags: ["authority", "classification-metadata"]
    
  - name: "EXECUTIVE_ORDER_REFERENCE"
    description: "Detects Executive Order classification references"
    type: "regex"
    pattern: "(?i)(E\\.?O\\.?\\s*1[23]\\d{3}|Executive\\s*Order\\s*1[23]\\d{3})"
    severity: "MEDIUM"
    category: "CLASSIFICATION_AUTHORITY"
    tags: ["executive-order", "authority"]

  # Declassification Markings
  - name: "DECLASSIFICATION_DATE"
    description: "Detects declassification date markings"
    type: "regex"
    pattern: "(?i)(Declassify\\s*On:|DG)\\s*\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4}"
    severity: "LOW"
    category: "DECLASSIFICATION"
    tags: ["declassification", "date"]
    
  - name: "DECLASSIFICATION_EVENT"
    description: "Detects event-based declassification markings"
    type: "regex"
    pattern: "(?i)(Declassify\\s*On:|DG)\\s*(OADR|MR|X\\d+)"
    severity: "LOW"
    category: "DECLASSIFICATION"
    tags: ["declassification", "event"]

  # Foreign Government Information
  - name: "FGI_MARKING"
    description: "Detects Foreign Government Information markings"
    type: "regex"
    pattern: "\\b(FGI|FOREIGN\\s*GOVERNMENT\\s*INFORMATION)\\b"
    severity: "HIGH"
    category: "FGI"
    tags: ["fgi", "foreign-government"]

  # NATO Classifications
  - name: "NATO_SECRET"
    description: "Detects NATO SECRET markings"
    type: "regex"
    pattern: "\\b(NATO\\s*SECRET|NS)\\b"
    severity: "HIGH"
    category: "NATO_CLASSIFICATION"
    tags: ["nato", "secret"]
    
  - name: "NATO_CONFIDENTIAL"
    description: "Detects NATO CONFIDENTIAL markings"
    type: "regex"
    pattern: "\\b(NATO\\s*CONFIDENTIAL|NC)\\b"
    severity: "MEDIUM"
    category: "NATO_CLASSIFICATION"
    tags: ["nato", "confidential"]

  # Warning Notices
  - name: "WARNING_NOTICE"
    description: "Detects classification warning notices"
    type: "regex"
    pattern: "(?i)(WARNING\\s*NOTICE|CLASSIFIED\\s*NATIONAL\\s*SECURITY\\s*INFORMATION)"
    severity: "HIGH"
    category: "WARNING"
    tags: ["warning", "notice"]

  # Atomic Energy Act Markings
  - name: "RD_MARKING"
    description: "Detects Restricted Data markings"
    type: "regex"
    pattern: "\\b(RD|RESTRICTED\\s*DATA)\\b"
    severity: "CRITICAL"
    category: "ATOMIC_ENERGY"
    tags: ["restricted-data", "atomic-energy"]
    
  - name: "FRD_MARKING"
    description: "Detects Formerly Restricted Data markings"
    type: "regex"
    pattern: "\\b(FRD|FORMERLY\\s*RESTRICTED\\s*DATA)\\b"
    severity: "HIGH"
    category: "ATOMIC_ENERGY"
    tags: ["formerly-restricted-data", "atomic-energy"]
    
  # DoD-Specific Markings
  - name: "FOUO_MARKING"
    description: "Detects For Official Use Only markings"
    type: "regex"
    pattern: "\\b(FOUO|FOR\\s*OFFICIAL\\s*USE\\s*ONLY)\\b"
    severity: "LOW"
    category: "DOD_SPECIFIC"
    tags: ["fouo", "sensitive-but-unclassified"]
    
  - name: "CUI_MARKING"
    description: "Detects Controlled Unclassified Information markings"
    type: "regex"
    pattern: "\\b(CUI|CONTROLLED\\s*UNCLASSIFIED\\s*INFORMATION)\\b"
    severity: "LOW"
    category: "CUI"
    tags: ["cui", "controlled-unclassified"]
    
  - name: "LES_MARKING"
    description: "Detects Law Enforcement Sensitive markings"
    type: "regex"
    pattern: "\\b(LES|LAW\\s*ENFORCEMENT\\s*SENSITIVE)\\b"
    severity: "MEDIUM"
    category: "LAW_ENFORCEMENT"
    tags: ["les", "law-enforcement"]
    
  - name: "LIMDIS_MARKING"
    description: "Detects Limited Distribution markings"
    type: "regex"
    pattern: "\\b(LIMDIS|LIMITED\\s*DISTRIBUTION)\\b"
    severity: "MEDIUM"
    category: "DISSEMINATION_CONTROL"
    tags: ["limdis", "limited-distribution"]

  # Classification Guide References
  - name: "CLASSIFICATION_GUIDE_REF"
    description: "Detects classification guide references"
    type: "regex"
    pattern: "(?i)(Classification\\s*Guide|CG\\s*\\d+|Security\\s*Classification\\s*Guide)"
    severity: "LOW"
    category: "CLASSIFICATION_AUTHORITY"
    tags: ["classification-guide", "authority"]
    
  # Date-based Declassification
  - name: "DECLASSIFICATION_25X"
    description: "Detects 25-year exemption markings"
    type: "regex"
    pattern: "(?i)(25X\\d+|Exempt\\s*from\\s*automatic\\s*declassification)"
    severity: "LOW"
    category: "DECLASSIFICATION"
    tags: ["declassification", "exemption"]

exclusions:
  - "SECRET\\s*(SERVICE|SANTA|SOCIETY|GARDEN|RECIPE|SHOPPER|MISSION|WEAPON|GOVERNMENT)"
  - "CONFIDENTIAL\\s*(ATTORNEY|MEDICAL|PATIENT|BUSINESS|INFORMATION|SOURCE|TREATMENT)"
  - "TOP\\s*SECRET\\s*(RECIPE|SAUCE|CLEARANCE)"
  - "CLASSIFIED\\s*(AD|ADVERTISEMENT|LISTING|SECTION)"
  - "FOR\\s*OFFICIAL\\s*USE\\s*ONLY\\s*(WHEN|IF|UNLESS)"